### ISSUE TITLE
How to use robot_controllers with a non-Fetch robot

### ISSUE THREAD

**Issue by pirobot** [fetchrobotics/robot_controllers#34]
We have been using the diff_drive_controller/DiffDriveController plugin in Gazebo 2.3 under ROS Indigo with a model of our custom robot (Jackrabbot) at Stanford University.  However, we have discovered that the robot rotates very slowly in Gazebo even with no Twist control input, in an empty world, and no matter how we set the pose and twist covariances.

We therefore wanted to try the robot_controllers/DiffDriveBaseController provided here since I noticed that the Fetch Gazebo model (also under ROS Indigo and Gazebo 2.3) does not have this rotation problem.

I include my YAML file below but the DiffDriveBaseController plugin is not being loaded when spawning our Jackrabbot model in Gazebo.  I noticed that with the Fetch gazebo launch file, the following lines at the end of the file fetch.gazebo.xacro:
```
<gazebo>
    <plugin name="fetch_gazebo_plugin" filename="libfetch_gazebo_plugin.so"/>
</gazebo>
```
are necessary for the DiffDriveBaseController plugin to be loaded.  My question is therefore, how can I get the DiffDriveBaseController plugin to load without using the fetch_gazebo_plugin which I am guessing is specific to the Fetch robot?

Thank you!  Here is my controllers yaml file:
```
base_controller:
  type: "robot_controllers/DiffDriveBaseController"
  autostart: true
  base_frame: sibot/base_link
  l_wheel_joint: "left_wheel"
  r_wheel_joint: "right_wheel"
  track_width: 0.542391
  radians_per_meter: 4.15682711
  publish_tf: true
  max_velocity_x: 3.57632
  max_velocity_r: 4.5
  max_acceleration_x: 0.75
  max_acceleration_r: 3.0
  publish_frequency: 100
  
gazebo:
  default_controllers:
    - "base_controller"
  l_wheel_joint:
    position:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 8.85
      d: 0.0
      i: 0.5
      i_clamp: 6.0
  r_wheel_joint:
    position:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 8.85
      d: 0.0
      i: 0.5
      i_clamp: 6.0
```
